/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export type {};

declare module "vue" {
	export interface GlobalComponents {
		ContextMenu: typeof import("./src/components/ContextMenu/index.vue")["default"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElContainer: typeof import("element-plus/es")["ElContainer"];
		ElDialog: typeof import("element-plus/es")["ElDialog"];
		ElFooter: typeof import("element-plus/es")["ElFooter"];
		ElForm: typeof import("element-plus/es")["ElForm"];
		ElFormItem: typeof import("element-plus/es")["ElFormItem"];
		ElHeader: typeof import("element-plus/es")["ElHeader"];
		ElInput: typeof import("element-plus/es")["ElInput"];
		ElMain: typeof import("element-plus/es")["ElMain"];
		ElOption: typeof import("element-plus/es")["ElOption"];
		ElSelect: typeof import("element-plus/es")["ElSelect"];
		ElTag: typeof import("element-plus/es")["ElTag"];
		Modal: typeof import("./src/components/Modal/index.vue")["default"];
		Toast: typeof import("./src/components/Toast/index.vue")["default"];
	}
}
