name: ✨ 功能请求
description: 提出新功能或改进建议
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！请简要描述您的需求。

  - type: dropdown
    id: feature-area
    attributes:
      label: 改进方面
      description: 这个功能涉及哪个方面？
      options:
        - UI界面 - 用户界面设计和交互
        - 功能逻辑 - 核心功能和业务逻辑
        - 性能优化 - 速度和效率提升
        - 用户体验 - 操作流程和易用性
        - 其他
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 为什么需要这个功能
      description: 描述您遇到的问题或需求
      placeholder: |
        现在使用时遇到的困难：...
        这个功能可以解决：...
        对用户的价值：...
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 希望实现的功能详述
      description: 详细描述您期望的功能如何工作
      placeholder: |
        功能描述：...
        操作流程：
        1. 用户点击...
        2. 系统显示...
        3. 用户可以...
        
        预期效果：...
    validations:
      required: true

  - type: textarea
    id: mockup-example
    attributes:
      label: 示例图或界面设计
      description: |
        建议附加简易示例图、界面截图或手绘草图来说明您的想法
        您可以直接将图片拖拽到这个区域，或描述界面布局
      placeholder: |
        界面布局描述：...
        或直接拖拽图片到此处
    validations:
      required: false