//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::{entity::prelude::*, ActiveValue::Set};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "env_config")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub id: String,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text")]
	pub scope: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub is_active: bool,
	pub sort: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::variable_group::Entity")]
	VariableGroup,
}

impl Related<super::variable_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::VariableGroup.def()
	}
}

impl ActiveModelBehavior for ActiveModel {
	fn new() -> Self {
		Self {
			id: Set(ulid::Ulid::new().to_string()),
			..ActiveModelTrait::default()
		}
	}
}
